# .air.toml
root = "../"
tmp_dir = "tmp"

[build]
  bin = "tmp/main.exe"
  cmd = "go build -o tmp/main.exe ."
  include_ext = ["go", "html", "css"]
  include_dir = ["backend", "views", "css"]

  exclude_dir = ["tmp", "node_modules"]

[log]
  level = "debug"

[runner]
  cmd = "tmp/main.exe"
  watch_delay = 10
